/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2017-01-09 14:56:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/bootstrap.css\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/bootstrap-responsive.css\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/style.css\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/superfish.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/jquery.ui.totop.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t//\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}); //\r\n");
      out.write("$(window).load(function() {\r\n");
      out.write("\t//\r\n");
      out.write("\r\n");
      out.write("}); //\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"top2_wrapper\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"span12\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"top2 clearfix\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"h1_wrapper\">\r\n");
      out.write("<div class=\"\">\r\n");
      out.write("<div class=\"\">\r\n");
      out.write("<div class=\"clearfix\">\r\n");
      out.write("<div class=\"h1_inner\">\r\n");
      out.write("<h1>About Our Company</h1>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"span12\">\r\n");
      out.write("\r\n");
      out.write("<h2>Who We Are</h2>\r\n");
      out.write("\r\n");
      out.write("<div class=\"thumb1\">\r\n");
      out.write("\t<div class=\"thumbnail clearfix\">\r\n");
      out.write("\t\t<figure class=\"img-polaroid\"><div class=\"figure_inner\"><img src=\"resources/images/about.jpg\" alt=\"\"></div></figure>\r\n");
      out.write("\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\tA bakery is an establishment that produces and sells flour-based food baked in an oven such as bread, cookies, cakes, pastries, and pies. Some retail bakeries ...Bakery businesses, together with tortilla manufacturing companies, employed about 18 percent of food manufacturing industry employees in 2008, according to ...\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<a href=\"#\" class=\"button1\">read more</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"line1\"></div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"span4\">\r\n");
      out.write("\r\n");
      out.write("<h3>Why Choose Us</h3>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("\t<b>\r\n");
      out.write("\t\tCake Nation offers a great service in the design, development, programming and marketing of your website. ... \r\n");
      out.write("\t</b>\r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("\t Sounds obvious but we listen to your ideas, plans and objectives for your business. ... Cake Nation is \"one-stop-shop\" web design agency providing everything you ...Practical, cost-effective service to clients.. All of our staff are driven by this client-focused tradition. As a result we are trusted to ensure our IT Solutions ...\r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<a href=\"#\" class=\"button1\">details</a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"span4\">\r\n");
      out.write("\r\n");
      out.write("<h3>Best Services</h3>\r\n");
      out.write("\r\n");
      out.write("<h5>Cupcakes</h5>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("\tOffers cupcakes, plus a selection for dogs. Includes daily menu with descriptions of each flavor, and online ordering for pick-up or local delivery.\r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<div class=\"line2\"></div>\r\n");
      out.write("\r\n");
      out.write("<h5>Birthday Cakes</h5>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("\tGiant Ice Cream Birthday Wishes Cake With Your Name.Print Name on Delicious Cake.Icecream Name Cake.Beautiful Pink Cake With Name.Best Wishes For ...\r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<div class=\"line2\"></div>\r\n");
      out.write("\r\n");
      out.write("<h5>Wedding Cakes</h5>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("\twedding cake...not a silver person so it would have to be gold with the diamond sparkle decoration...minus the bows and with coral plumarias...awww that is more ...\r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"span4\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"special2\">\r\n");
      out.write("<div class=\"spesial2_title\">Specials</div>\r\n");
      out.write("<img src=\"resources/images/special2.png\" alt=\"\" class=\"img\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
